# Generated by Django 5.0 on 2024-02-13 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_news_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 13, 17, 54, 1, 281338, tzinfo=datetime.timezone.utc)),
        ),
    ]
