# Generated by Django 4.2.10 on 2024-02-27 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_contactdata_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 13, 0, 12, 479878, tzinfo=datetime.timezone.utc)),
        ),
    ]
