# Generated by Django 4.2.10 on 2024-03-02 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_contact_alter_news_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 2, 12, 47, 14, 887104, tzinfo=datetime.timezone.utc)),
        ),
    ]
