# Generated by Django 5.0.3 on 2024-04-04 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_photo_en_profile_photo_ru_profile_photo_uz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo_ru',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo_uz',
        ),
    ]
