# Generated by Django 5.0.4 on 2026-03-28 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_photo_en_remove_profile_photo_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.TextField(blank=True, null=True),
        ),
    ]
